# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fan_constraint.xdc

# Block Designs: bd/bram/bram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram || ORIG_REF_NAME==bram} -quiet] -quiet

# IP: bd/bram/ip/bram_zynq_ultra_ps_e_0_0/bram_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==bram_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/bram/ip/bram_proc_sys_reset_0_0/bram_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_proc_sys_reset_0_0 || ORIG_REF_NAME==bram_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/bram/ip/bram_accel_top_0_1/bram_accel_top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_accel_top_0_1 || ORIG_REF_NAME==bram_accel_top_0_1} -quiet] -quiet

# IP: bd/bram/ip/bram_aes_accel_0_0/bram_aes_accel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_aes_accel_0_0 || ORIG_REF_NAME==bram_aes_accel_0_0} -quiet] -quiet

# XDC: c:/Users/nguye/Documents/GitHub/kria_kv260_vivado_bringup/kria/kria.gen/sources_1/bd/bram/bram_ooc.xdc
